AWSTemplateFormatVersion: "2010-09-09"
Description: OAF UAT Cluster

Parameters:
  ClusterName:
    Type: String
    Default: eks-uat-01
  KubernetesVersion:
    Type: String
    Default: "1.33"

Resources:
  ClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: eks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref ClusterName
      Version: !Ref KubernetesVersion
      RoleArn: !GetAtt ClusterRole.Arn
      ResourcesVpcConfig:
        SubnetIds: !Split [",", !ImportValue EKS-SUBNET-IDS]
        EndpointPublicAccess: true

Outputs:
  ClusterName:
    Value: !Ref EKSCluster
    Export:
      Name: EKS-CLUSTER-NAME

