AWSTemplateFormatVersion: "2010-09-09"
Description: OAF UAT Cluster Nodepool

Parameters:
  NodeInstanceType:
    Type: String
    Default: r6i.4xlarge

Resources:
  NodeInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

  NodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !ImportValue EKS-CLUSTER-NAME
      NodeRole: !GetAtt NodeInstanceRole.Arn
      Subnets: !Split [",", !ImportValue EKS-SUBNET-IDS]
      ScalingConfig:
        DesiredSize: 3
        MaxSize: 10
        MinSize: 3
      InstanceTypes:
        - !Ref NodeInstanceType
      AmiType: BOTTLEROCKET_x86_64
      NodegroupName: nodepool0

Outputs:
  NodeGroupName:
    Value: !Ref NodeGroup

